# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JuiceMenu',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.FloatField()),
            ],
        ),
    ]
